# Generated by Django 5.0 on 2025-05-25 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisBahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=255)),
                ('kode_komponen', models.CharField(choices=[('baterai', 'BATERAI'), ('casing', 'CASING'), ('charger', 'CHARGER'), ('gpu', 'GPU'), ('kamera', 'KAMERA'), ('layar', 'LAYAR'), ('penyimpanan', 'PENYIMPANAN'), ('prosesor', 'PROSESOR'), ('ram', 'RAM')], max_length=15)),
                ('status_eco_friendly', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_merk', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_gpu', models.CharField(blank=True, default='Default Judul', max_length=255)),
                ('tipe_gpu', models.CharField(choices=[('integrated', 'INTEGRATED'), ('discrete', 'DISCRETE')], max_length=25)),
                ('model_gpu', models.CharField(max_length=255)),
                ('memori_gpu', models.CharField(max_length=255)),
                ('keperluan', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jenisbahan')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_charger', models.CharField(blank=True, default='Judul Default', max_length=255)),
                ('seri_charger', models.CharField(max_length=255)),
                ('tipe_port', models.CharField(choices=[('usb-a', 'USB-A'), ('usb-c', 'USB-C'), ('magsafe', 'MAGSAFE')], max_length=10)),
                ('teknologi_charger', models.CharField(choices=[('quick charger', 'QUICK CHARGER'), ('power delivery', 'POWER DELIVERY'), ('vooc', 'VOOC')], max_length=40)),
                ('kompatibilitas_tegangan', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jenisbahan')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_casing', models.CharField(blank=True, default='Default Judul', max_length=255)),
                ('seri_casing', models.CharField(max_length=255)),
                ('ventilasi', models.CharField(choices=[('fan', 'FAN'), ('airflow', 'AIRFLOW')], max_length=20)),
                ('panjang', models.IntegerField()),
                ('lebar', models.IntegerField()),
                ('tinggi', models.IntegerField()),
                ('warna', models.TextField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jenisbahan')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.CreateModel(
            name='Baterai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_baterai', models.CharField(blank=True, default='Judul Default', max_length=255)),
                ('seri_baterai', models.CharField(max_length=255)),
                ('kapasitas', models.IntegerField()),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jenisbahan')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.CreateModel(
            name='Kamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_kamera', models.CharField(blank=True, default='Judul Default', max_length=255)),
                ('resolusi', models.IntegerField()),
                ('tipe_lensa', models.CharField(choices=[('wide', 'WIDE'), ('ultrawide', 'ULTRAWIDE'), ('telephoto', 'TELEPHOTO'), ('makro', 'MAKRO')], max_length=25)),
                ('seri_kamera', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jenisbahan')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_laptop', models.CharField(blank=True, default='Judul Default', max_length=255)),
                ('upload_foto', models.ImageField(upload_to='media/laptop/%Y/%m/%d/')),
                ('jenis_warna', models.CharField(max_length=100)),
                ('ukuran', models.IntegerField()),
                ('kapasitas', models.IntegerField()),
                ('status_eco_friendly', models.BooleanField(blank=True)),
                ('qr_code_laptop', models.ImageField(upload_to='media/barcode_produk/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baterai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baterai')),
                ('casing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.casing')),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.charger')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gpu')),
                ('kamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kamera')),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_komentar', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balasan', to='api.komentar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='api.laptop')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Layar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_layar', models.CharField(blank=True, default='Judul Default', max_length=255)),
                ('seri_layar', models.CharField(max_length=255)),
                ('panjang_layar', models.IntegerField()),
                ('lebar_layar', models.IntegerField()),
                ('resolusi', models.CharField(choices=[('hd', 'HD'), ('full hd', 'FULL HD'), ('2k', '2K'), ('4k', '4K')], max_length=10)),
                ('refresh_rate', models.CharField(choices=[('60hz', '60HZ'), ('90hz', '90HZ'), ('120hz', '120HZ'), ('144hz', '144HZ')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jenisbahan')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='layar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.layar'),
        ),
        migrations.CreateModel(
            name='Penyimpanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_penyimpanan', models.CharField(blank=True, default='Default Judul', max_length=255)),
                ('seri_penyimpan', models.CharField(max_length=255)),
                ('kapasitas_penyimpanan', models.IntegerField()),
                ('kecepatan_baca_tulis', models.CharField(max_length=255)),
                ('form_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jenis_penyimpanan', models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD'), ('emmc', 'eMMC'), ('ufs', 'UFS')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jenisbahan')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='penyimpanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.penyimpanan'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('pria', 'PRIA'), ('wanita', 'WANITA')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media/profile/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prosesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_prosesor', models.CharField(blank=True, default='Default Judul', max_length=255)),
                ('seri_prosesor', models.CharField(max_length=255)),
                ('jumlah_core', models.IntegerField()),
                ('kecepatan_clock', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arsitektur', models.CharField(choices=[('x86', 'X86'), ('arm', 'ARM'), ('arm64', 'ARM64')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jenisbahan')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='prosesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prosesor'),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_ram', models.CharField(blank=True, default='Default Judul', max_length=255)),
                ('jenis_ram', models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5'), ('lpddr', 'LPDDR')], max_length=10)),
                ('kapasitas_ram', models.IntegerField()),
                ('kecepatan_ram', models.IntegerField()),
                ('cas_latency', models.IntegerField()),
                ('seri_ram', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jenisbahan')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ram'),
        ),
        migrations.CreateModel(
            name='Seri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_seri', models.CharField(blank=True, max_length=255)),
                ('nama_seri', models.CharField(max_length=255)),
                ('tahun_seri', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merk')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='seri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seri'),
        ),
    ]
