# Generated by Django 5.0 on 2025-05-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baterai',
            name='judul_baterai',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='casing',
            name='judul_casing',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='casing',
            name='warna',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='charger',
            name='judul_charger',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='judul_gpu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='kamera',
            name='judul_kamera',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='judul_laptop',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='layar',
            name='judul_layar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='penyimpanan',
            name='judul_penyimpanan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prosesor',
            name='judul_prosesor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ram',
            name='judul_ram',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
