# Generated by Django 5.0 on 2025-05-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_baterai_judul_baterai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='qr_code_laptop',
            field=models.ImageField(blank=True, upload_to='media/barcode_produk/%Y/%m/%d/'),
        ),
    ]
