# Generated by Django 5.0 on 2025-06-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_laptop_qr_code_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='merk',
            name='img_merk',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/%Y/%m/%d/'),
        ),
    ]
